apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-app
  labels:
    app: student-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management-container
          # Image construite et pouss√©e sur Docker Hub
          image: akrout2000/gestion-etudiante:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: student-config
            - secretRef:
                name: mysql-pass-secret
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-management
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089
  selector:
    app: student-management
