---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/springdb"

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==        # "root"
  SPRING_DATASOURCE_PASSWORD: cm9vdDEyMw==   # "root123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: tshiivaa/student-management:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret

---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
